[package]
name = "brave_pilot"
version = "0.1.0"
authors = ["MintCollie <dragoncool57@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
autopilot = "0.4.0"
rand = "0.7.3"
enigo = "0.0.13"